on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node v19.3.0
        uses: actions/setup-node@v3
        with:
          node-version: 19.3.0
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1